### ISSUE TITLE
Automatically choose x86 or x64 dll

### ISSUE THREAD

**Issue by huan086** [StefH/MediaInfo.DotNetWrapper#1]
Use LoadLibraryEx and do it like https://github.com/cschlote/MediaInfoDotNet/blob/master/MediaInfoDotNet/MediaInfoDLL.cs#L206

**Comment by StefH** [comment]
I'm not sure if I need this code because the 'after build' target from `MediaInfo.Native.0.7.92.1` copies the correct dll version to the output folder.

**Comment by huan086** [comment]
Problem is that I can't choose AnyCPU. When I choose x64 as target, Entity Framework migration in Visual Studio doesn't work, as VS runs as x86. Would be great if both x86 and x64 DLL are present to have both VS x86 and IIS x64 work (using AnyCPU)

**Comment by StefH** [comment]
Can you provide an example console app which has this issue ?

**Comment by huan086** [comment]
The EF6 code first project below should show my point
http://www.entityframeworktutorial.net/entityframework6/sample-project.aspx

Set your project to target x64. Then in package manager console, run Update-Database

EF6 will give
`System.BadImageFormatException: Could not load file or assembly '' or one of its dependencies. An attempt was made to load a program with an incorrect format.`

Since my project targets x64 for IIS, but needs to be in x86 for EF to work, ideally I would choose AnyCPU. However, DotNetWrapper does not allow me to set my target as AnyCPU.

**Comment by StefH** [comment]
This cannot be done because the `"MediaInfo.Native": "0.7.92.1"` only copies one dll version to the output folder.

**Comment by huan086** [comment]
Any idea where is the repo for "MediaInfo.Native"?

**Comment by StefH** [comment]
Maybe here:
https://github.com/yartat/MP-MediaInfo
