### ISSUE TITLE
Using NuGet Package with ClickOnce Deployment

### ISSUE THREAD

**Issue by suchja** [StefH/MediaInfo.DotNetWrapper#9]
Actually this seems not to be your fault, but it is not possible to use this nuget-package in combination with a clickonce deployment. Although there is no error, the problem is that ClickOnce does not see the dependency to MediaInfo.Native. Thus it does not add it to the installation and on application start all DLLs from MediaInfo.Native are not available and thus my application crashes.

I'm not an expert with NuGet, but do you think there is some other way to make your dependency on MediaInfo.Native more obvious? Or do you know of any way to properly install an application using your NuGet package?

I do need to find some way to install my application using your NuGet package and the required MediaInfo.dll (and its dependencies) in an easy way. - Thank you so much for your effort!

**Comment by StefH** [comment]
Quick question; did you try to build your app as x64 or 32 ?

**Comment by suchja** [comment]
Thanks for your immediate feedback. I tried both, but would be happy with x64 in the first try :-(

**Comment by suchja** [comment]
Just created a quick example to show the problem: https://github.com/suchja/MediaInfoConsole

When preparing to deploy this solution the `MediaInfo.Native` package and its included DLLs like `MediaInfo.dll` do **not** appear in the corresponding wizard (sorry for the German UI).
<img width="1237" alt="bildschirmfoto 2018-03-28 um 02 44 57" src="https://user-images.githubusercontent.com/3649865/38002384-47b01cac-3232-11e8-8232-dc3feb654aad.png">

I tried it once again with `x86` and `x64` and in addition with `Debug` and `Release`. It is the same in all combinations.

While inspecting the project file I found [this entry](https://github.com/suchja/MediaInfoConsole/blob/5cf4c7a743e36a25bf030e0459e964aa0ab7f0c1/MediaInfoConsole/MediaInfoConsole.vbproj#L187). This seems to me like a first indication why all the other DLLs are not recognised by ClickOnce. You link the project which seems to be build during application build and not the already build DLL like you did it for [MediaInfo.DotNetWrapper.dll](https://github.com/suchja/MediaInfoConsole/blob/5cf4c7a743e36a25bf030e0459e964aa0ab7f0c1/MediaInfoConsole/MediaInfoConsole.vbproj#L111).

**Comment by StefH** [comment]
A workaround which could work:

Just add the 5 dll's from the packages folder (`....\MediaInfo.DotNetWrapper\packages\MediaInfo.Native.17.12\build\native\x86`) or x64 to your project.

And set **Copy if newer** to true for all these dll's


When inspecting the clickone files, you see that the dll's are included:
![dlls](https://user-images.githubusercontent.com/249938/38012856-48933704-3263-11e8-9d3c-d55afb9f81c5.png)

**Comment by suchja** [comment]
Yeah, did that already as workaround. However, would be good to have a proper solution which builds for x86 and x64.

**Comment by StefH** [comment]
Another solution would be to add a post-build step and just copy the correct dll's from the packages\MediaInfo.Native.17.12\build\native\... folder ?

Or conditionally include the dll's, by manually editing the csproj file?

**Comment by suchja** [comment]
That probably will do. Thank you! Will update this issue once I have it running, so the solution is documented.
